### PR TITLE
Change params same with juggler

### PR DESCRIPTION
**Pull request by kimkha**
The function will call from here: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L1743

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kimkha** [comment]
Sorry, what's wrong with my PR?

**Comment by dhmlau** [comment]
It complains about your commit messages being too long: 
```
**  Linting commit logs
**
**  2 problems found:
**    1b0657a - Change params to match with juggler: line 3 longer than 72 characters.
**    29e9b17 - Change params to match with datasource-juggler: line 3 longer than 72 characters.
```
If you click the Details link next to Commit Linter, you'd see more details.

**Comment by kimkha** [comment]
So, what should I do now?

**Comment by dhmlau** [comment]
I'd suggest you to squash the 2 commits and make the commit message to be less than 72 characters per line (see https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/contrib/git-commit-messages.md).  

To begin, you can run `git rebase -i`.
More info can be found here: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History, or search for `how to squash git commit`. 

Hope it helps.

**Comment by kimkha** [comment]
Moved to #143

**Pull request closed without merging**
