### PR TITLE
Identity column haven't been correctly identified

### PR DESCRIPTION
**Pull request by richardaum**
https://github.com/strongloop/loopback-connector-mssql/issues/81

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
LGTM, can you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-connector-mssql

**Comment by richardaum** [comment]
@superkhau OK! No problem :)

**Comment by superkhau** [comment]
Can you add some tests to verify your changes and prevent regressions in the future?

**Comment by richardaum** [comment]
@superkhau How can I do it?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@richardaum Could you please sign the CLA and add some unit tests so we can proceed with this PR? https://cla.strongloop.com/agreements/strongloop/loopback-connector-mssql

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by acclaimuser** [comment]
This is still an issue.

**Pull request closed without merging**
