### PR TITLE
Fixed multiple primary keys and only one belongsTo relation generated from mssql juggler 2.19.0

### PR DESCRIPTION
**Pull request by ebenmoha**
There was a bug where only one belongsTo relation is generated and many foreignkeys were flaggued with identity attribute (primary key).

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ebenmoha** [comment]
The primary key part of this PR is already evoked in this PR : https://github.com/strongloop/loopback-connector-mssql/pull/99

**Comment by ebenmoha** [comment]
I decided to continue on myself. I added support for many to many relations

**Pull request closed without merging**
