### PR TITLE
Use juggler@3 for running tests

### PR DESCRIPTION
**Pull request by superkhau**
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1038

### CODE REVIEW

**Comment by bajtos** [comment]
test please

**Comment by bajtos** [comment]
@superkhau it seems to me that this connector was not passing on CI even before the change in this pull request. In that case I think it's ok to land this patch as it is now. We should create a `P1 #tob` issue to get the CI fixed as soon as feasible.

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
>We should create a P1 #tob issue to get the CI fixed as soon as feasible.

There is already an issue created on @loay plate at https://github.com/strongloop-internal/scrum-loopback/issues/1006, I bumped it to P1.

**Comment by superkhau** [comment]
test please

**Pull request merged**
