### PR TITLE
Inject PARTITION BY clause for 'where' filter followed by 'limit' filter

### PR DESCRIPTION
**Pull request by eugene-frb**
Removed original version of buildColumnNames from previous pull request at 

https://github.com/strongloop/loopback-connector-mssql/pull/57

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by eugene-frb** [comment]
Please ignore my previous pull request at 

https://github.com/strongloop/loopback-connector-mssql/pull/57

which duplicated buildColumnNames function by keeping its original version.

**Comment by raymondfeng** [comment]
@eugene-frb Both commits in the PR were from @sam-github. Where is your change?

**Comment by eugene-frb** [comment]
Hi Raymond, something went wrong with my check-in. I re-created the same pull request at 

https://github.com/strongloop/loopback-connector-mssql/pull/59

It should have the changes now.

**Comment by raymondfeng** [comment]
Replaced by https://github.com/strongloop/loopback-connector-mssql/pull/59

**Pull request closed without merging**
