### PR TITLE
#158 Adding extra clause for Buffer type parameter processing

### PR DESCRIPTION
**Pull request by riekjurg**
### Description
 Adding extra clause for Buffer type parameter processing.

#### Related issues
#158 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@riekjurg Thank you for the patch. Could you please add some test cases to validate your fix?

Please fix the commit message as well. The first line of the commit message needs to be less than 50 characters long.

Also please sign the [**Contributors License Agreement**](https://cla.strongloop.com/agreements/strongloop/loopback-connector-mssql).

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ludem** [comment]
I'm facing the same issue (can't save a buffer to db) and this patch resolves it. Please merge this commit.

**Comment by prespic** [comment]
Can we reopen and merge this PR? This feature is really missing.

**Pull request closed without merging**
