### PR TITLE
Throw an error if there is no PK column to prevent unhelpful errors being returned

### PR DESCRIPTION
**Pull request by rjbez17**
Throw an error if there is no PK column to prevent unhelpful errors being returned

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
We could add an optional arg to `idName(model, throwIfNotFound)`

**Comment by rjbez17** [comment]
We could do that too. Let me know what you think is best. I think adding it to idName might be best.

**Comment by raymondfeng** [comment]
+1 to enhance `idName()`. BTW, should it `throw` or report the error via `cb`?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
