### PR TITLE
Added support to unicode

### PR DESCRIPTION
**Pull request by ahmed-abdulmoniem**
Added support to unicode by adding N prefix

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ahmed-abdulmoniem** [comment]
Should I add this comment or one of the admins?

**Comment by ahmed-abdulmoniem** [comment]
@raymondfeng Can you review it?

**Comment by superkhau** [comment]
@ahmed-abdulmoniem LGTM.

@raymondfeng Can I merge?

**Comment by raymondfeng** [comment]
ok to test

**Comment by ahmed-abdulmoniem** [comment]
Thank you guys

**Pull request merged**
