### PR TITLE
#21 Fix for Insert into Table with Active Trigger

### PR DESCRIPTION
**Pull request by FoysalOsmany**
Issue: https://github.com/strongloop/loopback-connector-mssql/issues/21

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@FoysalOsmany Can you sign the CLA - https://cla.strongloop.com/agreements/strongloop/loopback-connector-mssql?

**Comment by raymondfeng** [comment]
ok to test

**Comment by FoysalOsmany** [comment]
@raymondfeng I signed the CLA

**Comment by FoysalOsmany** [comment]
@raymondfeng Can you please review and should I have to do anything to merge this pull request?

**Comment by FoysalOsmany** [comment]
@raymondfeng Can you please check and merge the pull request? otherwise I have to maintain my own fork.

**Pull request merged**
