### PR TITLE
Master

### PR DESCRIPTION
**Pull request by charlee1005**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ssh24** [comment]
What is this PR for? Looks like someone just rebased the crap out of their master and did a PR from there...

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@ssh24 Let's just close this PR. It's obviously a mess.

@charlee1005 Please submit a new PR that is updated with a description of the feature you're trying to integrate into this repo.

See http://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request for how to actually submit a PR properly.

**Comment by charlee1005** [comment]
Yeah,  I'm sorry but I have no idea what any of this even is.  I didn't submit anything, and everything  in the link is a foreign language  to me.  My accounts have been and are comprised. Don't know how to stop it.  Just don't use them often anymore.  Sorry for any trouble. 
--------------------------------------------
On Tue, 3/21/17, Simon Ho <notifications@github.com> wrote:

 Subject: Re: [strongloop/loopback-connector-mssql] Master (#86)
 To: "strongloop/loopback-connector-mssql" <loopback-connector-mssql@noreply.github.com>
 Cc: "charlee1005" <charlee1005@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, March 21, 2017, 2:59 PM
 
 Closed #86.
 
 -- 
 You are receiving this because you were mentioned.
 Reply to this email directly or view it on GitHub:
 https://github.com/strongloop/loopback-connector-mssql/pull/86#event-1009472412

**Comment by superkhau** [comment]
@charlee1005 No problem. Hope all is well now. ;)

**Pull request closed without merging**
