### PR TITLE
Add support for custom mapping, idInjection and generated

### LINKED ISSUE #1: idInjection not working
I set idInjection option to false and the mssql still creates an id PK field.

### PR DESCRIPTION
**Pull request by idosh**
Add support for custom column mapping in primary key column
Add support for idInjection

Closes #1

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by idosh** [comment]
.ok\W+to\W+test.

**Comment by idosh** [comment]
".ok\W+to\W+test."

**Comment by idosh** [comment]
ok to test

**Comment by raymondfeng** [comment]
@idosh Thank you for the patch. Would you please add a test case?

**Comment by idosh** [comment]
@raymondfeng I added a new test case

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
