### PR TITLE
Update migration.js

### PR DESCRIPTION
**Pull request by ataft**
Execute alterTable statements in order

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by ataft** [comment]
Any updates on this?

**Comment by agnes512** [comment]
Could you add tests for the change? I think https://github.com/strongloop/loopback-connector-mssql/blob/master/test/autoupdate.test.js might be a good place 😄  thanks!

**Comment by ataft** [comment]
The current test already covers this PR because it does an automigrate (create the table) on [line 135](https://github.com/strongloop/loopback-connector-mssql/blob/master/test/autoupdate.test.js#L135) and then an autoupdate on [line 155](https://github.com/strongloop/loopback-connector-mssql/blob/master/test/autoupdate.test.js#L155), which will call alterTable. BTW, this test should be failing intermittently, but given that the order is random it'd be hard to catch.

**Comment by agnes512** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by agnes512** [comment]
@slnode test please

**Comment by jannyHou** [comment]
dropping node 8 in https://github.com/strongloop/loopback-connector-mssql/pull/230, hope it fixes the error

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
rebased the PR, let me trigger a new build and merge

**Comment by jannyHou** [comment]
merged 🎉 thank you @ataft for the contribution again!

**Pull request merged**
