### PR TITLE
Update Discovery Queries to Uppercase

### PR DESCRIPTION
**Pull request by reajuria**
#### Related issues

- connect to #178 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by reajuria** [comment]
Hi @jannyHou querying information schema views in a Case Sensitive environment would fire an SQL exception, check [Information Schema Views Docs](https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql?view=sql-server-2017) starting from MSSQL 2008

**Comment by jannyHou** [comment]
@reajuria Great that is the perfect reference. Your PR LGTM, landed it. 🚢 
And thank you again for improving our connector align with the new standard!

**Pull request merged**
