### PR TITLE
Enable clean DB seed as pre-test

### PR DESCRIPTION
**Pull request by ssh24**
Currently, mssql just uses a shared db instance which does not seed the database before the test. This PR allows to seed the database clean for every CI build.

connect to https://github.com/strongloop-internal/scrum-apex/issues/190

### CODE REVIEW

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
This PR might not be a healthy addition to our code-base. The CI looks to run the windows/linux builds simultaneously and run into a race condition when trying to seed the database for each build.

@rmg Any thoughts on this? As you said previously, we do not trigger the build in a sequence (i.e wait for linux builds to finish before starting windows), this PR might be an impossible case with a shared db.

**Comment by ssh24** [comment]
This PR has to be held off for a while till we figure out a way to not use a shared mssql database for CI. Closing this as a case.

**Comment by ssh24** [comment]
Nvm, opening it back. Looks like node-6 windows is failing on master for CI. http://ci.strongloop.com/job/loopback-connector-mssql/node=6.x,os=windows/1738/console

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
