### PR TITLE
parsing parameterized SQL does not work

### PR DESCRIPTION
**Pull request by eugene-frb**
Extra parenthesis around parameter's placeholder while parsing
parameterized SQL in mssql connector

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@eugene-frb Thanks for the patch. Please sign CLA at https://cla.strongloop.com/agreements/strongloop/loopback-connector-mssql

**Comment by raymondfeng** [comment]
1. There is one more place that references `(?)`: https://github.com/eugene-frb/loopback-connector-mssql/blob/master/lib/mssql.js#L133

2. Can you just update your native SQL to use `(?)` as the place holder for parameters instead of changing the MSSQL connector?

3. We also need to exclude the occurrences of placeholder within string or id literals (`'` or `"`)

**Comment by eugene-frb** [comment]
Using (?) worked. Thank you, Raymond!

**Pull request closed without merging**
